version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:latest-jdk17
    privileged: true
    user: jenkins
    networks:
      infrastructure:
        aliases:
          - jenkins-docker
    ports:
      - 50000:50000
    container_name: jenkins
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home:rw,z
      - ./jenkins/ssh/id_rsa:/var/jenkins_home/.ssh/id_ed25519

  agent:
    image: agent
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
    platform: linux/amd64
    networks:
      infrastructure:
        aliases:
          - agent-docker
    container_name: agent
    volumes:
      - ./jenkins/jenkins_agent:/home/jenkins:rw,z
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./jenkins/ssh/id_rsa.pub:/home/jenkins/.ssh/authorized_keys

  jfrog:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    networks:
      infrastructure:
        aliases:
          - jfrog-docker
    container_name: jfrog
    volumes:
      - ./jfrog/jfrog-home:/var/opt/jfrog/artifactory/:rw,z

  gateway:
    image: nginx
    volumes:
      - ./nginx/custom.conf:/etc/nginx/conf.d/default.conf:rw,z
    ports:
      - "80:80"
    container_name: gateway
    networks:
        infrastructure:
          aliases:
            - nginx-docker

networks:
  infrastructure:
    name: infrastructure
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
