version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:2.414.1-lts-jdk17
    privileged: true
    user: jenkins
    networks:
      infrastructure:
        aliases: 
          - jenkins-docker
    ports:
      - 8088:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home:rw,z
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./jenkins/ssh/id_rsa:/var/jenkins_home/.ssh/id_rsa
  
  agent:
    image: agent
    privileged: true
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      infrastructure:
        aliases: 
          - agent-docker
    container_name: agent
    volumes:
      - ./jenkins/jenkins_agent:/home/jenkins:rw,z
      - /var/run/docker.sock:/var/run/docker.sock:z
      - ./jenkins/ssh/id_rsa:/home/jenkins/.ssh/authorized_keys

networks:
  infrastructure:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
