apiVersion: v1
kind: Service
metadata:
  name: artifactory-service
spec:
  ports:
    - port: 8081
      name: artifactory
      targetPort: 8081
    - port: 8082
      name: ui
      targetPort: 8082
  selector:
    app: artifactory-service