apiVersion: v1
kind: Service
metadata:
  name: artifactory-service
spec:
  ports:
    - port: 8081
      name: artifactory-port
      targetPort: artifactory
    - port: 8082
      name: ui-port
      targetPort: ui-port
  selector:
    app: artifactory-deployment