apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-gateway
  namespace: devops-tools
spec:
  rules:
  - host: "jenkins-minikube"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jenkins-service
            port:
              number: 8080