apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-gateway
  namespace: devops-tools
spec:
  rules:
  - host: "jenkins-minikube"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jenkins-service
            port:
              number: 8080
  - host: "artifactory-minikube"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: artifactory-service
            port:
              number: 8082
  - host: "database-minikube"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: database-service
            port:
              number: 5432
  - host: "sonarqube-minikube"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sonarqube-service
            port:
              number: 9000