apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-deployment
  template:
    metadata:
      labels:
        app: jenkins-deployment
    spec:
      securityContext:
        fsGroup: 1000 
      containers:
      - name: jenkins
        imagePullPolicy: IfNotPresent
        image: jenkins/jenkins:latest-jdk17
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-data
            mountPath: /var/jenkins_home
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "1024Mi"
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pv-claim