apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins-service

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins-service