apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-deployment
  template:
    metadata:
      labels:
        app: database-deployment
    spec:
      securityContext:
        fsGroup: 1000 
        runAsUser: 1000
      containers:
      - name: postgres
        imagePullPolicy: IfNotPresent
        image: bitnami/postgresql:15.3.0-debian-11-r77
        ports:
          - name: "database-port"
            containerPort: 5432
            protocol: "TCP"
        volumeMounts:
          - name: "database-volume"
            mountPath: "/bitnami/postgresql"
            subPath: "postgres-data"
            readOnly: false
        envFrom:
          - configMapRef:
              name: "database-configmap"
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: "1024Mi"
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: database-pv-claim