version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:2.414.1-lts-jdk17
    privileged: true
    user: jenkins
    networks:
      jenkins:
        aliases: 
          - jenkins-docker
    ports:
      - 8088:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home:rw,z
      - /var/run/docker.sock:/var/run/docker.sock:z
  
  agent:
    image: ubuntu:latest
    privileged: true
    user: root
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      jenkins:
        aliases: 
          - agent-docker
    container_name: agent
    volumes:
      - ./jenkins_agent:/home/jenkins:rw,z
      - /var/run/docker.sock:/var/run/docker.sock:z

networks:
  jenkins:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16