pipeline {
  agent {
    label 'agent-docker'
  }

  options {
    buildDiscarder(logRotator(daysToKeepStr: "14", numToKeepStr: "5"))
    disableConcurrentBuilds(abortPrevious: true)
    timeout(time: 30, unit: 'MINUTES')
  }

  stages {
    stage("Build environment information") {
      steps {
        sh "whoami"
        sh "printenv"
        sh "pwd"
        sh "uname -a"
      }
    }

    stage('Docker step') {
      agent {
        docker { image 'node:18.17.1-alpine3.18' }
      }
      steps {
          sh 'node --version'
      }
    }
  }
  
}
