apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- jenkins/service.yaml
- jenkins/volume.yaml
- jenkins/deployment.yaml

- ingress/gateway.yaml

- artifactory/service.yaml
- artifactory/volume.yaml
- artifactory/deployment.yaml

- database/configmap.yaml
- database/service.yaml
- database/volume.yaml
- database/deployment.yaml

- sonarqube/service.yaml
- sonarqube/volume.yaml
- sonarqube/deployment.yaml
- sonarqube/configmap.yaml

