pipeline {
  agent {
    label 'agent-docker'
  }

  tools {
    maven '3.9.4'
  }

  environment {
    CI = true
    ARTIFACTORY_ACCESS_TOKEN = credentials('artifactory-access-token')
  }

  options {
    buildDiscarder(logRotator(daysToKeepStr: "14", numToKeepStr: "5"))
    disableConcurrentBuilds(abortPrevious: true)
    timeout(time: 30, unit: 'MINUTES')
  }

  stages {

    stage("Build environment information") {
      steps {
        sh "whoami"
        sh "printenv"
      }
    }

    stage("Build Java Module") {
        steps {
            dir("jfrog/demo") {
                sh "mvn clean install"
            }
        }
    }

    stage("Upload to Artifactory") {
        // agent {
        //     docker {
        //         image 'releases-docker.jfrog.io/jfrog/jfrog-cli-v2:2.2.0'
        //         args  '--network="infrastructure"'
        //         reuseNode true
        //     }
        // }
        steps{
            dir("jfrog/demo") {
                sh 'jf rt upload --url http://jfrog-docker:8082/artifactory/ --access-token ${ARTIFACTORY_ACCESS_TOKEN} target/demo-0.0.1-SNAPSHOT.jar maven-repo/demo/' 
            }
        }
    }

  }
}
